/**
 * Created by apple12 on 2016/12/18.
 */

export const LOAD_MOVIES_REQUEST = "LOAD_MOVIES_REQUEST";
export const LOAD_MOVIES_SUCCESS = "LOAD_MOVIES_SUCCESS";
export const LOAD_MOVIES_FAILURE = "LOAD_MOVIES_FAILURE";

export const LOAD_DETAIL_REQUEST = "LOAD_DETAIL_REQUEST";
export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_FAILURE = "LOAD_DETAIL_FAILURE";